things related to GNU build tools (almost done, now i get only a few problems at linking time)

diff --git a/trunk/apertium-service/configure b/trunk/apertium-service/configure
--- a/trunk/apertium-service/configure
+++ b/trunk/apertium-service/configure
@@ -638,6 +638,10 @@ ac_includes_default="\
 
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
+APERTIUM_LIBS
+APERTIUM_CFLAGS
+LTTOOLBOX_LIBS
+LTTOOLBOX_CFLAGS
 XMLPP_LIBS
 XMLPP_CFLAGS
 PKG_CONFIG
@@ -745,7 +749,11 @@ CFLAGS
 CPP
 PKG_CONFIG
 XMLPP_CFLAGS
-XMLPP_LIBS'
+XMLPP_LIBS
+LTTOOLBOX_CFLAGS
+LTTOOLBOX_LIBS
+APERTIUM_CFLAGS
+APERTIUM_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1391,6 +1399,14 @@ Some influential environment variables:
   XMLPP_CFLAGS
               C compiler flags for XMLPP, overriding pkg-config
   XMLPP_LIBS  linker flags for XMLPP, overriding pkg-config
+  LTTOOLBOX_CFLAGS
+              C compiler flags for LTTOOLBOX, overriding pkg-config
+  LTTOOLBOX_LIBS
+              linker flags for LTTOOLBOX, overriding pkg-config
+  APERTIUM_CFLAGS
+              C compiler flags for APERTIUM, overriding pkg-config
+  APERTIUM_LIBS
+              linker flags for APERTIUM, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -5755,6 +5771,242 @@ else
 $as_echo "yes" >&6; }
 	:
 fi
+
+
+
+
+
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for LTTOOLBOX" >&5
+$as_echo_n "checking for LTTOOLBOX... " >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LTTOOLBOX_CFLAGS"; then
+        pkg_cv_LTTOOLBOX_CFLAGS="$LTTOOLBOX_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"lttoolbox-3.1 >= 3.1.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "lttoolbox-3.1 >= 3.1.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LTTOOLBOX_CFLAGS=`$PKG_CONFIG --cflags "lttoolbox-3.1 >= 3.1.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LTTOOLBOX_LIBS"; then
+        pkg_cv_LTTOOLBOX_LIBS="$LTTOOLBOX_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"lttoolbox-3.1 >= 3.1.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "lttoolbox-3.1 >= 3.1.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LTTOOLBOX_LIBS=`$PKG_CONFIG --libs "lttoolbox-3.1 >= 3.1.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        LTTOOLBOX_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "lttoolbox-3.1 >= 3.1.0"`
+        else
+	        LTTOOLBOX_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "lttoolbox-3.1 >= 3.1.0"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$LTTOOLBOX_PKG_ERRORS" >&5
+
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (lttoolbox-3.1 >= 3.1.0) were not met:
+
+$LTTOOLBOX_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables LTTOOLBOX_CFLAGS
+and LTTOOLBOX_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+$as_echo "$as_me: error: Package requirements (lttoolbox-3.1 >= 3.1.0) were not met:
+
+$LTTOOLBOX_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables LTTOOLBOX_CFLAGS
+and LTTOOLBOX_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { $as_echo "$as_me:$LINENO: error: in \`$ac_pwd':" >&5
+$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
+{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables LTTOOLBOX_CFLAGS
+and LTTOOLBOX_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables LTTOOLBOX_CFLAGS
+and LTTOOLBOX_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }; }
+else
+	LTTOOLBOX_CFLAGS=$pkg_cv_LTTOOLBOX_CFLAGS
+	LTTOOLBOX_LIBS=$pkg_cv_LTTOOLBOX_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
+
+
+
+
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for APERTIUM" >&5
+$as_echo_n "checking for APERTIUM... " >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$APERTIUM_CFLAGS"; then
+        pkg_cv_APERTIUM_CFLAGS="$APERTIUM_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"apertium-3.1 >= 3.1.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "apertium-3.1 >= 3.1.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_APERTIUM_CFLAGS=`$PKG_CONFIG --cflags "apertium-3.1 >= 3.1.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$APERTIUM_LIBS"; then
+        pkg_cv_APERTIUM_LIBS="$APERTIUM_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"apertium-3.1 >= 3.1.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "apertium-3.1 >= 3.1.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_APERTIUM_LIBS=`$PKG_CONFIG --libs "apertium-3.1 >= 3.1.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        APERTIUM_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "apertium-3.1 >= 3.1.0"`
+        else
+	        APERTIUM_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "apertium-3.1 >= 3.1.0"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$APERTIUM_PKG_ERRORS" >&5
+
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (apertium-3.1 >= 3.1.0) were not met:
+
+$APERTIUM_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables APERTIUM_CFLAGS
+and APERTIUM_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+$as_echo "$as_me: error: Package requirements (apertium-3.1 >= 3.1.0) were not met:
+
+$APERTIUM_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables APERTIUM_CFLAGS
+and APERTIUM_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { $as_echo "$as_me:$LINENO: error: in \`$ac_pwd':" >&5
+$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
+{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables APERTIUM_CFLAGS
+and APERTIUM_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables APERTIUM_CFLAGS
+and APERTIUM_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }; }
+else
+	APERTIUM_CFLAGS=$pkg_cv_APERTIUM_CFLAGS
+	APERTIUM_LIBS=$pkg_cv_APERTIUM_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
+
 
 
 
